### ISSUE TITLE
Specificity issue with slotted elements

### ISSUE THREAD

**Issue by mindthetic** [webcomponents/webcomponentsjs#898]
In Firefox when I apply styles inside a custom element they are stronger than styles applied externally.

The below example

```html
<custom-element>
   <h1 class="green">Title</h1>
</div>
```
```css
.green {
    color: green;
}
```
custom-element.html
```css
:host .wrapper ::slotted(*) {
    color: red;
}
```

Will appear red in Firefox because when the polyfill runs it outputs

```css
custom-element .wrapper * {
    color: red;
}
```

which is more specific than
```css
.green {
    color: green;
}
```

Anyone experience this problem before?
